spring:
  application:
    name: eureka-server
#eureka config#
eureka:
  client:
    prefer-same-zone-eureka: true
      region: tianjin
#      availability-zones:
#        tianjin: tj-zone-1,tj-zone-2
    service-url:
      defaultZones: http://192.168.1.112:1111/eureka
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

