spring:
  application:
    name: eureka-server
#eureka config#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.97:1111/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ly-eureka-server

